### ISSUE TITLE
Support redirection of aliases

### ISSUE THREAD

**Issue by markdumay** [markdumay/hugo-theme-vanity#1]
The theme should support aliases to allow importing of packages with subdirectories. An alias can be defined as such:
```yaml
---
title: "gorram"
date: 2021-09-14T13:20:55+02:00
draft: false
repository: github.com/natefinch/gorram
godoc: pkg.go.dev/npf.io/gorram
tags: [package]
aliases: [
    "/gorram/run",
    "/gorram/cli",
]
---
```

Either `example.org/gorram`, `example.org/gorram/run`, or `example.org/gorram/cli` should resolve correctly.
